apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: solar-system-appset
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: sandbox   
  template:
    metadata:
      name: '{{namespace}}-solar-system-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/mnsajmi/gitops-argocd.git
        targetRevision: main
        path: solar-system
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
