apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: solar-system-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: https://kubernetes.default.svc
            namespace: solar-system-dev
          - cluster: https://kubernetes.default.svc
            namespace: solar-system-prod
  template:
    metadata:
      name: '{{namespace}}-solar-system-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/<username>/gitops-argocd
        targetRevision: main
        path: solar-system
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
